version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]